### ISSUE TITLE
Update curl URL

### ISSUE THREAD

**Issue by milsyobtaf** [fourkitchens/train-headless#37]
At the end of book section 2, `curl http://mirzu.fourword.webchefs.org:8080/api/v1.0/blogposts \
-H "X-API-Version: v1.0"` should reflect the student's URLs

**Comment by mirzu** [comment]
This is fixed and I've created a user named `finished` that works so students can copy and paste easily. 
```
curl http://finished.drupal.headless.4kclass.com:8080/api/articles \
-H "X-API-Version: v1.0"
```
