### ISSUE TITLE
Update API URL

### ISSUE THREAD

**Issue by milsyobtaf** [fourkitchens/train-headless#38]
In section four of the book, `Hey look at that someone created a categories endpoint for us: /api/categories. Open up the folder and take quick look, we didn’t need to do anything besides declare the class.` should point to /api/blog_categories

**Comment by mirzu** [comment]
This is right now. 
![2__drupal_services___headless_training_book](https://cloud.githubusercontent.com/assets/251658/8584132/444a1ab6-2599-11e5-9267-008e64b1b2ea.png)
